#!/bin/bash

# ios2android - a simple script to port iOS retina images to the appropriate Android density buckets
#
# For more information: https://github.com/Ninjanetic/ios2android

# The MIT License (MIT)

# Copyright (c) 2013 Ninjanetic Design Inc.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Requires Imagemagick
# To install on Mac: brew install imagemagick

# Floating point number functions from http://www.linuxjournal.com/content/floating-point-math-bash

#####################################################################
# Default scale used by float functions.

float_scale=2


#####################################################################
# Evaluate a floating point number expression.

function float_eval()
{
    local stat=0
    local result=0.0
    if [[ $# -gt 0 ]]; then
        result=$(echo "scale=$float_scale; $*" | bc -q 2>/dev/null)
        stat=$?
        if [[ $stat -eq 0  &&  -z "$result" ]]; then stat=1; fi
    fi
    echo $result
    return $stat
}

#####################################################################
# Process images.

rm -rf drawable-mdpi
rm -rf drawable-hdpi
rm -rf drawable-xhdpi
rm -rf drawable-xxhdpi
mkdir drawable-mdpi
mkdir drawable-hdpi
mkdir drawable-xhdpi
mkdir drawable-xxhdpi

for ii in *.jpg *.png; do 
    if [ -f $ii ];
    then
        x=${ii/@3x./.}
        if [[ ${x} =~ -568h ]]; then
            x=${x/-568h./.}
        fi
        x=${x//-/_}

        if [[ ${x} =~ ^[0-9] ]]; then
            x="img_${x}"
        fi

        x=`echo $x | tr "[:upper:]" "[:lower:]"`
        echo $ii
        convert -resize 33.3% $ii drawable-mdpi/$x
        convert -resize 50% $ii drawable-hdpi/$x
        convert -resize 66.6% $ii drawable-xhdpi/$x
        convert -resize 100% $ii drawable-xxhdpi/$x        
    fi
done